apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-api
spec:
  template:
    spec:
      containers:
      - name: booking-api
        image: cmonthe8/booking-api:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  template:
    spec:
      containers:
      - name: user-api
        image: cmonthe8/user-api:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
spec:
  template:
    spec:
      containers:
      - name: payment-api
        image: cmonthe8/payment-api:latest
