apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-frontend
  template:
    metadata:
      labels:
        app: nginx-frontend
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: nginx
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/nginx-frontend:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend-service
spec:
  type: NodePort
  selector:
    app: nginx-frontend
  ports:
  - port: 80
    targetPort: 8080
