apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - booking-deployment.yaml
  - user-deployment.yaml
  - payment-deployment.yaml
  - nginx-deployment.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: monthe-booking
