apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: user-api
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/user-api:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-api
  ports:
  - port: 80
    targetPort: 8080
